### ISSUE TITLE
Need to add line, Vector only shows option to add point.

### ISSUE THREAD

**Issue by numbershikes** [SteveCline/vector#2]
Hi Steve, I really like the snap function in Vector.rocks and how quickly it updates compared to other editors I've used.

How does Vector determine whether the 'Create new feature' option will be for a point, line, or polygon for a particular imported layer? It seems to vary depending on the file.

I need to add a line to a certain GeoJSON file, but Vector only shows a button to create a point. Is there a way to enable the other feature types as well?

**Comment by SteveCline** [comment]
vector was mostly designed for classic GIS folks, so it only supports 1 geometry type for a geojson file, much like shapefiles. If the geojson has multiple geometry types it will take the type of the very first feature. At this time, I want to keep it as it is. thanks for using it!
